//! OpenMLS Flutter Bindings
//!
//! This crate mirrors the API surface of `openmls-uniffi` but uses
//! `flutter_rust_bridge` (FRB v2) to generate Dart bindings for Flutter,
//! instead of Mozilla UniFFI (Swift/Kotlin).

mod frb_generated; /* Auto-generated by flutter_rust_bridge_codegen */
#[macro_use]
pub mod api;
