[package]
name = "openmls_flutter"
version = "0.1.0"
authors = ["OpenMLS Authors"]
edition = "2021"
license = "MIT"
publish = false

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "openmls_flutter"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(frb_expand)'] }

[dependencies]
flutter_rust_bridge = "=2.13.0"
openmls-bindings-core = { path = "../openmls-bindings" }
anyhow = "1"
log = "0.4"

[target.'cfg(target_os = "android")'.dependencies]
android_logger = "0.14"
